<?php
// $Id: sln.module,v 1.1.4.4 2008/04/14 00:34:55 kmillecam Exp $

/**
 * Implementation of hook_user().
 */
function sln_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'load':
      if(arg(0) == 'user') {
        return sln_load_user($account);
      }
    case 'update':
    case 'insert':
    case 'form':
    case 'register':
    case 'delete':
      break;
  }
}

/* Custom access denied -function */
function sln_access_denied() {
  drupal_set_header('HTTP/1.1 403 Forbidden');

  watchdog('access denied', check_plain($_GET['q']), NULL, WATCHDOG_WARNING);

  drupal_set_title(t('Access denied'));
  return t('You are not authorized to access this page.');
}

/**
 * Implementation of hook_perm().
 */
function sln_perm() {
  $perms = array('view archived chat');

  return $perms;
}

/**
 * Inject information on a user load.
 *
 * @param object $account
 *   User object passed by reference.
 */
function sln_load_user(&$account) {
  $dob_field = _birthdays_get_field(variable_get('birthdays_field_id', 'profile_dob'));

  // Pre-load birthday-information into $account
  profile_load_profile($account);

  // If it was set by the user
  if ($account->{$dob_field->name}) {
    //$account->{$dob_field->name} = 'Ikä';
    // Set the user's age
    $date = $account->profile_dob['year'] . '-' . $account->profile_dob['month'] . '-' . $account->profile_dob['day'];
    $years = sln_age($date);
    $account->age =  $years . 'v';
  }
}

function sln_age($date, $round = 2) {
  $seconds = time() - strtotime($date);
  $years = round(($seconds / 31556926),$round);
  return $years;
}